### PR TITLE
Update name of the project

### PR DESCRIPTION
**Pull request by ZackUnfair**
Hello, I noticed that the name of your project was wrong, so I updated it for you :smiley:

### CODE REVIEW

**Comment by Aecheritt** [comment]
How Unfair

**Comment by Weeping-Cat** [comment]
God damn you

**Comment by ZackUnfair** [comment]
@Weeping-Cat @Cascascap @Unbancho @LukasSnoeck 
I'd like each of you to review my code, if you don't mind :100:

**Comment by Cascascap** [comment]
Looks good, approved.

**Comment by ZackUnfair** [comment]
wow rude

**Pull request merged**
